// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package amazonsqsconnector.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import amazonsqsconnector.AmazonHelper;
import software.amazon.awssdk.services.sqs.SqsClient;
import software.amazon.awssdk.services.sqs.model.CreateQueueRequest;

public class CreateQueue extends CustomJavaAction<java.lang.String>
{
	private java.lang.String name;
	private IMendixObject __config;
	private amazonsqsconnector.proxies.AwsConfig config;

	public CreateQueue(IContext context, java.lang.String name, IMendixObject config)
	{
		super(context);
		this.name = name;
		this.__config = config;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		this.config = __config == null ? null : amazonsqsconnector.proxies.AwsConfig.initialize(getContext(), __config);

		// BEGIN USER CODE
		SqsClient sqs = AmazonHelper.getSqsClient(config);
		
		CreateQueueRequest createQueueRequest = CreateQueueRequest.builder()
				.queueName(name)
				.build();
		return sqs.createQueue(createQueueRequest).queueUrl(); 
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "CreateQueue";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
