// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package amazonsqsconnector.actions;

import java.util.LinkedList;
import java.util.List;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import amazonsqsconnector.AmazonHelper;
import amazonsqsconnector.proxies.Queue;
import software.amazon.awssdk.services.sqs.SqsClient;
import software.amazon.awssdk.services.sqs.model.ListQueuesResponse;

public class ListQueues extends CustomJavaAction<java.util.List<IMendixObject>>
{
	private IMendixObject __config;
	private amazonsqsconnector.proxies.AwsConfig config;

	public ListQueues(IContext context, IMendixObject config)
	{
		super(context);
		this.__config = config;
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		this.config = __config == null ? null : amazonsqsconnector.proxies.AwsConfig.initialize(getContext(), __config);

		// BEGIN USER CODE
		List<IMendixObject> result = new LinkedList<>();
		SqsClient sqs = AmazonHelper.getSqsClient(config);
		
		ListQueuesResponse res = sqs.listQueues();
		
		for(String queueUrl : res.queueUrls()) {
			Queue q = new Queue(getContext());
			q.setUrl(queueUrl);
			result.add(q.getMendixObject());
		}
		return result;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ListQueues";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
