// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package amazonsqsconnector.actions;

import java.util.LinkedList;
import java.util.List;
import java.util.Map.Entry;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import amazonsqsconnector.AmazonHelper;
import software.amazon.awssdk.services.sqs.SqsClient;
import software.amazon.awssdk.services.sqs.model.Message;
import software.amazon.awssdk.services.sqs.model.MessageSystemAttributeName;
import software.amazon.awssdk.services.sqs.model.QueueAttributeName;
import software.amazon.awssdk.services.sqs.model.ReceiveMessageRequest;

public class ReceiveMessage extends CustomJavaAction<IMendixObject>
{
	private java.lang.String queueUrl;
	private java.lang.Long waitTimeSeconds;
	private java.lang.Boolean includeAttributes;
	private IMendixObject __config;
	private amazonsqsconnector.proxies.AwsConfig config;

	public ReceiveMessage(IContext context, java.lang.String queueUrl, java.lang.Long waitTimeSeconds, java.lang.Boolean includeAttributes, IMendixObject config)
	{
		super(context);
		this.queueUrl = queueUrl;
		this.waitTimeSeconds = waitTimeSeconds;
		this.includeAttributes = includeAttributes;
		this.__config = config;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		this.config = __config == null ? null : amazonsqsconnector.proxies.AwsConfig.initialize(getContext(), __config);

		// BEGIN USER CODE
		SqsClient sqs = AmazonHelper.getSqsClient(config);
		
		List<QueueAttributeName> attributes = new LinkedList<>();
		if (includeAttributes) {
			attributes.add(QueueAttributeName.ALL);
		}
		
		ReceiveMessageRequest receiveMessageRequest = ReceiveMessageRequest.builder()
				.queueUrl(queueUrl)
				.attributeNames(attributes)
				.messageAttributeNames(MessageSystemAttributeName.SENDER_ID.name(), 
						MessageSystemAttributeName.SENT_TIMESTAMP.name())
				.maxNumberOfMessages(1)
				.waitTimeSeconds(waitTimeSeconds.intValue())
				.build();

		List<Message> messages = sqs.receiveMessage(receiveMessageRequest).messages();
		if (messages.size() == 0) {
			return null;
		}
		Message message = messages.get(0);
		return AmazonHelper.getMendixMessageFromSQSMessage(getContext(), message).getMendixObject();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ReceiveMessage";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
