// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package amazonsqsconnector.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import amazonsqsconnector.AmazonHelper;
import software.amazon.awssdk.services.sqs.SqsClient;
import software.amazon.awssdk.services.sqs.model.SendMessageRequest;

public class SendMessage extends CustomJavaAction<java.lang.Void>
{
	private java.lang.String body;
	private java.lang.String queueUrl;
	private IMendixObject __config;
	private amazonsqsconnector.proxies.AwsConfig config;

	public SendMessage(IContext context, java.lang.String body, java.lang.String queueUrl, IMendixObject config)
	{
		super(context);
		this.body = body;
		this.queueUrl = queueUrl;
		this.__config = config;
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		this.config = __config == null ? null : amazonsqsconnector.proxies.AwsConfig.initialize(getContext(), __config);

		// BEGIN USER CODE
		SqsClient sqs = AmazonHelper.getSqsClient(config);
		
		SendMessageRequest req = SendMessageRequest.builder()
				.queueUrl(queueUrl)
				.messageBody(body)
				.build();
		sqs.sendMessage(req);
		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "SendMessage";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
