// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package amazonsqsconnector.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the AmazonSQSConnector module
	public static boolean afterStartup(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		return (java.lang.Boolean) Core.microflowCall("AmazonSQSConnector.AfterStartup").withParams(params).execute(context);
	}
	public static boolean bCo_AwsConfig(IContext context, amazonsqsconnector.proxies.AwsConfig _awsConfig)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("AwsConfig", _awsConfig == null ? null : _awsConfig.getMendixObject());
		return (java.lang.Boolean) Core.microflowCall("AmazonSQSConnector.BCo_AwsConfig").withParams(params).execute(context);
	}
	public static amazonsqsconnector.proxies.QueueAttributes dS_GetQueueAttributes(IContext context, amazonsqsconnector.proxies.Queue _queue)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Queue", _queue == null ? null : _queue.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("AmazonSQSConnector.DS_GetQueueAttributes").withParams(params).execute(context);
		return result == null ? null : amazonsqsconnector.proxies.QueueAttributes.initialize(context, result);
	}
	public static java.util.List<amazonsqsconnector.proxies.Queue> dS_GetQueues(IContext context, amazonsqsconnector.proxies.AwsConfig _awsConfig)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("AwsConfig", _awsConfig == null ? null : _awsConfig.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("AmazonSQSConnector.DS_GetQueues").withParams(params).execute(context);
		java.util.List<amazonsqsconnector.proxies.Queue> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(amazonsqsconnector.proxies.Queue.initialize(context, obj));
		}
		return result;
	}
	public static java.util.List<amazonsqsconnector.proxies.Message> dS_Receive10MessagesFromQueue(IContext context, amazonsqsconnector.proxies.Queue _queue)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Queue", _queue == null ? null : _queue.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("AmazonSQSConnector.DS_Receive10MessagesFromQueue").withParams(params).execute(context);
		java.util.List<amazonsqsconnector.proxies.Message> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(amazonsqsconnector.proxies.Message.initialize(context, obj));
		}
		return result;
	}
	public static void iVK_CreateQueue(IContext context, amazonsqsconnector.proxies.CreateQueueRequest _createQueueRequest)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("CreateQueueRequest", _createQueueRequest == null ? null : _createQueueRequest.getMendixObject());
		Core.microflowCall("AmazonSQSConnector.IVK_CreateQueue").withParams(params).execute(context);
	}
	public static void iVK_CreateQueueRequest(IContext context, amazonsqsconnector.proxies.AwsConfig _awsConfig)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("AwsConfig", _awsConfig == null ? null : _awsConfig.getMendixObject());
		Core.microflowCall("AmazonSQSConnector.IVK_CreateQueueRequest").withParams(params).execute(context);
	}
	public static void iVK_DeleteMessage(IContext context, amazonsqsconnector.proxies.Message _message)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Message", _message == null ? null : _message.getMendixObject());
		Core.microflowCall("AmazonSQSConnector.IVK_DeleteMessage").withParams(params).execute(context);
	}
	public static void iVK_DeleteQueue(IContext context, amazonsqsconnector.proxies.Queue _queue)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Queue", _queue == null ? null : _queue.getMendixObject());
		Core.microflowCall("AmazonSQSConnector.IVK_DeleteQueue").withParams(params).execute(context);
	}
	public static void iVK_GetSingleMessage(IContext context, amazonsqsconnector.proxies.Queue _queue, amazonsqsconnector.proxies.AwsConfig _config)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Queue", _queue == null ? null : _queue.getMendixObject());
		params.put("Config", _config == null ? null : _config.getMendixObject());
		Core.microflowCall("AmazonSQSConnector.IVK_GetSingleMessage").withParams(params).execute(context);
	}
	public static void iVK_OpenReceive10Messages(IContext context, amazonsqsconnector.proxies.Queue _queue)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Queue", _queue == null ? null : _queue.getMendixObject());
		Core.microflowCall("AmazonSQSConnector.IVK_OpenReceive10Messages").withParams(params).execute(context);
	}
	public static void iVK_PurgeQueue(IContext context, amazonsqsconnector.proxies.Queue _queue, amazonsqsconnector.proxies.AwsConfig _awsConfig)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Queue", _queue == null ? null : _queue.getMendixObject());
		params.put("AwsConfig", _awsConfig == null ? null : _awsConfig.getMendixObject());
		Core.microflowCall("AmazonSQSConnector.IVK_PurgeQueue").withParams(params).execute(context);
	}
	public static void iVK_SaveAwsConfig(IContext context, amazonsqsconnector.proxies.AwsConfig _awsConfig)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("AwsConfig", _awsConfig == null ? null : _awsConfig.getMendixObject());
		Core.microflowCall("AmazonSQSConnector.IVK_SaveAwsConfig").withParams(params).execute(context);
	}
	public static void iVK_SendMessage(IContext context, amazonsqsconnector.proxies.SendMessageRequest _sendMessageRequest)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("SendMessageRequest", _sendMessageRequest == null ? null : _sendMessageRequest.getMendixObject());
		Core.microflowCall("AmazonSQSConnector.IVK_SendMessage").withParams(params).execute(context);
	}
	public static void iVK_SendMessageRequest(IContext context, amazonsqsconnector.proxies.AwsConfig _awsConfig, amazonsqsconnector.proxies.Queue _queue)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("AwsConfig", _awsConfig == null ? null : _awsConfig.getMendixObject());
		params.put("Queue", _queue == null ? null : _queue.getMendixObject());
		Core.microflowCall("AmazonSQSConnector.IVK_SendMessageRequest").withParams(params).execute(context);
	}
}