// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package amazonsqsconnector.proxies;

public class CognitoConfig extends amazonsqsconnector.proxies.AwsConfig
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AmazonSQSConnector.CognitoConfig";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Username("Username"),
		Password("Password"),
		IdentityPoolId("IdentityPoolId"),
		Identifier("Identifier"),
		AccessKey("AccessKey"),
		SecretKey("SecretKey"),
		RegionName("RegionName"),
		SelectedRegion("AmazonSQSConnector.SelectedRegion");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public CognitoConfig(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "AmazonSQSConnector.CognitoConfig"));
	}

	protected CognitoConfig(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject cognitoConfigMendixObject)
	{
		super(context, cognitoConfigMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("AmazonSQSConnector.CognitoConfig", cognitoConfigMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a AmazonSQSConnector.CognitoConfig");
	}

	/**
	 * @deprecated Use 'CognitoConfig.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static amazonsqsconnector.proxies.CognitoConfig initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return amazonsqsconnector.proxies.CognitoConfig.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static amazonsqsconnector.proxies.CognitoConfig initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new amazonsqsconnector.proxies.CognitoConfig(context, mendixObject);
	}

	public static amazonsqsconnector.proxies.CognitoConfig load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return amazonsqsconnector.proxies.CognitoConfig.initialize(context, mendixObject);
	}

	public static java.util.List<amazonsqsconnector.proxies.CognitoConfig> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<amazonsqsconnector.proxies.CognitoConfig> result = new java.util.ArrayList<amazonsqsconnector.proxies.CognitoConfig>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//AmazonSQSConnector.CognitoConfig" + xpathConstraint))
			result.add(amazonsqsconnector.proxies.CognitoConfig.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of Username
	 */
	public final java.lang.String getUsername()
	{
		return getUsername(getContext());
	}

	/**
	 * @param context
	 * @return value of Username
	 */
	public final java.lang.String getUsername(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Username.toString());
	}

	/**
	 * Set value of Username
	 * @param username
	 */
	public final void setUsername(java.lang.String username)
	{
		setUsername(getContext(), username);
	}

	/**
	 * Set value of Username
	 * @param context
	 * @param username
	 */
	public final void setUsername(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String username)
	{
		getMendixObject().setValue(context, MemberNames.Username.toString(), username);
	}

	/**
	 * @return value of Password
	 */
	public final java.lang.String getPassword()
	{
		return getPassword(getContext());
	}

	/**
	 * @param context
	 * @return value of Password
	 */
	public final java.lang.String getPassword(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Password.toString());
	}

	/**
	 * Set value of Password
	 * @param password
	 */
	public final void setPassword(java.lang.String password)
	{
		setPassword(getContext(), password);
	}

	/**
	 * Set value of Password
	 * @param context
	 * @param password
	 */
	public final void setPassword(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String password)
	{
		getMendixObject().setValue(context, MemberNames.Password.toString(), password);
	}

	/**
	 * @return value of IdentityPoolId
	 */
	public final java.lang.String getIdentityPoolId()
	{
		return getIdentityPoolId(getContext());
	}

	/**
	 * @param context
	 * @return value of IdentityPoolId
	 */
	public final java.lang.String getIdentityPoolId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.IdentityPoolId.toString());
	}

	/**
	 * Set value of IdentityPoolId
	 * @param identitypoolid
	 */
	public final void setIdentityPoolId(java.lang.String identitypoolid)
	{
		setIdentityPoolId(getContext(), identitypoolid);
	}

	/**
	 * Set value of IdentityPoolId
	 * @param context
	 * @param identitypoolid
	 */
	public final void setIdentityPoolId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String identitypoolid)
	{
		getMendixObject().setValue(context, MemberNames.IdentityPoolId.toString(), identitypoolid);
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final amazonsqsconnector.proxies.CognitoConfig that = (amazonsqsconnector.proxies.CognitoConfig) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "AmazonSQSConnector.CognitoConfig";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
