// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package amazonsqsconnector.proxies;

public class Message
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject messageMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AmazonSQSConnector.Message";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		MessageId("MessageId"),
		ReceiptHandle("ReceiptHandle"),
		MD5OfBody("MD5OfBody"),
		Body("Body"),
		SenderId("SenderId"),
		SentTimestamp("SentTimestamp"),
		Message_Queue("AmazonSQSConnector.Message_Queue");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Message(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "AmazonSQSConnector.Message"));
	}

	protected Message(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject messageMendixObject)
	{
		if (messageMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("AmazonSQSConnector.Message", messageMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a AmazonSQSConnector.Message");

		this.messageMendixObject = messageMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Message.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static amazonsqsconnector.proxies.Message initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return amazonsqsconnector.proxies.Message.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static amazonsqsconnector.proxies.Message initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new amazonsqsconnector.proxies.Message(context, mendixObject);
	}

	public static amazonsqsconnector.proxies.Message load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return amazonsqsconnector.proxies.Message.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of MessageId
	 */
	public final java.lang.String getMessageId()
	{
		return getMessageId(getContext());
	}

	/**
	 * @param context
	 * @return value of MessageId
	 */
	public final java.lang.String getMessageId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MessageId.toString());
	}

	/**
	 * Set value of MessageId
	 * @param messageid
	 */
	public final void setMessageId(java.lang.String messageid)
	{
		setMessageId(getContext(), messageid);
	}

	/**
	 * Set value of MessageId
	 * @param context
	 * @param messageid
	 */
	public final void setMessageId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String messageid)
	{
		getMendixObject().setValue(context, MemberNames.MessageId.toString(), messageid);
	}

	/**
	 * @return value of ReceiptHandle
	 */
	public final java.lang.String getReceiptHandle()
	{
		return getReceiptHandle(getContext());
	}

	/**
	 * @param context
	 * @return value of ReceiptHandle
	 */
	public final java.lang.String getReceiptHandle(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ReceiptHandle.toString());
	}

	/**
	 * Set value of ReceiptHandle
	 * @param receipthandle
	 */
	public final void setReceiptHandle(java.lang.String receipthandle)
	{
		setReceiptHandle(getContext(), receipthandle);
	}

	/**
	 * Set value of ReceiptHandle
	 * @param context
	 * @param receipthandle
	 */
	public final void setReceiptHandle(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String receipthandle)
	{
		getMendixObject().setValue(context, MemberNames.ReceiptHandle.toString(), receipthandle);
	}

	/**
	 * @return value of MD5OfBody
	 */
	public final java.lang.String getMD5OfBody()
	{
		return getMD5OfBody(getContext());
	}

	/**
	 * @param context
	 * @return value of MD5OfBody
	 */
	public final java.lang.String getMD5OfBody(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MD5OfBody.toString());
	}

	/**
	 * Set value of MD5OfBody
	 * @param md5ofbody
	 */
	public final void setMD5OfBody(java.lang.String md5ofbody)
	{
		setMD5OfBody(getContext(), md5ofbody);
	}

	/**
	 * Set value of MD5OfBody
	 * @param context
	 * @param md5ofbody
	 */
	public final void setMD5OfBody(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String md5ofbody)
	{
		getMendixObject().setValue(context, MemberNames.MD5OfBody.toString(), md5ofbody);
	}

	/**
	 * @return value of Body
	 */
	public final java.lang.String getBody()
	{
		return getBody(getContext());
	}

	/**
	 * @param context
	 * @return value of Body
	 */
	public final java.lang.String getBody(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Body.toString());
	}

	/**
	 * Set value of Body
	 * @param body
	 */
	public final void setBody(java.lang.String body)
	{
		setBody(getContext(), body);
	}

	/**
	 * Set value of Body
	 * @param context
	 * @param body
	 */
	public final void setBody(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String body)
	{
		getMendixObject().setValue(context, MemberNames.Body.toString(), body);
	}

	/**
	 * @return value of SenderId
	 */
	public final java.lang.String getSenderId()
	{
		return getSenderId(getContext());
	}

	/**
	 * @param context
	 * @return value of SenderId
	 */
	public final java.lang.String getSenderId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SenderId.toString());
	}

	/**
	 * Set value of SenderId
	 * @param senderid
	 */
	public final void setSenderId(java.lang.String senderid)
	{
		setSenderId(getContext(), senderid);
	}

	/**
	 * Set value of SenderId
	 * @param context
	 * @param senderid
	 */
	public final void setSenderId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String senderid)
	{
		getMendixObject().setValue(context, MemberNames.SenderId.toString(), senderid);
	}

	/**
	 * @return value of SentTimestamp
	 */
	public final java.util.Date getSentTimestamp()
	{
		return getSentTimestamp(getContext());
	}

	/**
	 * @param context
	 * @return value of SentTimestamp
	 */
	public final java.util.Date getSentTimestamp(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.SentTimestamp.toString());
	}

	/**
	 * Set value of SentTimestamp
	 * @param senttimestamp
	 */
	public final void setSentTimestamp(java.util.Date senttimestamp)
	{
		setSentTimestamp(getContext(), senttimestamp);
	}

	/**
	 * Set value of SentTimestamp
	 * @param context
	 * @param senttimestamp
	 */
	public final void setSentTimestamp(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date senttimestamp)
	{
		getMendixObject().setValue(context, MemberNames.SentTimestamp.toString(), senttimestamp);
	}

	/**
	 * @return value of Message_Queue
	 */
	public final amazonsqsconnector.proxies.Queue getMessage_Queue() throws com.mendix.core.CoreException
	{
		return getMessage_Queue(getContext());
	}

	/**
	 * @param context
	 * @return value of Message_Queue
	 */
	public final amazonsqsconnector.proxies.Queue getMessage_Queue(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		amazonsqsconnector.proxies.Queue result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Message_Queue.toString());
		if (identifier != null)
			result = amazonsqsconnector.proxies.Queue.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Message_Queue
	 * @param message_queue
	 */
	public final void setMessage_Queue(amazonsqsconnector.proxies.Queue message_queue)
	{
		setMessage_Queue(getContext(), message_queue);
	}

	/**
	 * Set value of Message_Queue
	 * @param context
	 * @param message_queue
	 */
	public final void setMessage_Queue(com.mendix.systemwideinterfaces.core.IContext context, amazonsqsconnector.proxies.Queue message_queue)
	{
		if (message_queue == null)
			getMendixObject().setValue(context, MemberNames.Message_Queue.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Message_Queue.toString(), message_queue.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return messageMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final amazonsqsconnector.proxies.Message that = (amazonsqsconnector.proxies.Message) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "AmazonSQSConnector.Message";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
