// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package amazonsqsconnector.proxies;

public class QueueAttributes
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject queueAttributesMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AmazonSQSConnector.QueueAttributes";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ApproximateNumberOfMessages("ApproximateNumberOfMessages"),
		ApproximateNumberOfMessagesDelayed("ApproximateNumberOfMessagesDelayed"),
		ApproximateNumberOfMessagesNotVisible("ApproximateNumberOfMessagesNotVisible"),
		CreatedTimestamp("CreatedTimestamp"),
		DelaySeconds("DelaySeconds"),
		FIFOQueue("FIFOQueue"),
		LastModifiedTimestamp("LastModifiedTimestamp"),
		MaximumMessageSize("MaximumMessageSize"),
		MessageRetentionPeriod("MessageRetentionPeriod"),
		ARN("ARN"),
		VisibilityTimeout("VisibilityTimeout"),
		ReceiveMessageWaitTimeSeconds("ReceiveMessageWaitTimeSeconds"),
		QueueAttributes_Queue("AmazonSQSConnector.QueueAttributes_Queue");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public QueueAttributes(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "AmazonSQSConnector.QueueAttributes"));
	}

	protected QueueAttributes(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject queueAttributesMendixObject)
	{
		if (queueAttributesMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("AmazonSQSConnector.QueueAttributes", queueAttributesMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a AmazonSQSConnector.QueueAttributes");

		this.queueAttributesMendixObject = queueAttributesMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'QueueAttributes.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static amazonsqsconnector.proxies.QueueAttributes initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return amazonsqsconnector.proxies.QueueAttributes.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static amazonsqsconnector.proxies.QueueAttributes initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new amazonsqsconnector.proxies.QueueAttributes(context, mendixObject);
	}

	public static amazonsqsconnector.proxies.QueueAttributes load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return amazonsqsconnector.proxies.QueueAttributes.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of ApproximateNumberOfMessages
	 */
	public final java.lang.Integer getApproximateNumberOfMessages()
	{
		return getApproximateNumberOfMessages(getContext());
	}

	/**
	 * @param context
	 * @return value of ApproximateNumberOfMessages
	 */
	public final java.lang.Integer getApproximateNumberOfMessages(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.ApproximateNumberOfMessages.toString());
	}

	/**
	 * Set value of ApproximateNumberOfMessages
	 * @param approximatenumberofmessages
	 */
	public final void setApproximateNumberOfMessages(java.lang.Integer approximatenumberofmessages)
	{
		setApproximateNumberOfMessages(getContext(), approximatenumberofmessages);
	}

	/**
	 * Set value of ApproximateNumberOfMessages
	 * @param context
	 * @param approximatenumberofmessages
	 */
	public final void setApproximateNumberOfMessages(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer approximatenumberofmessages)
	{
		getMendixObject().setValue(context, MemberNames.ApproximateNumberOfMessages.toString(), approximatenumberofmessages);
	}

	/**
	 * @return value of ApproximateNumberOfMessagesDelayed
	 */
	public final java.lang.Integer getApproximateNumberOfMessagesDelayed()
	{
		return getApproximateNumberOfMessagesDelayed(getContext());
	}

	/**
	 * @param context
	 * @return value of ApproximateNumberOfMessagesDelayed
	 */
	public final java.lang.Integer getApproximateNumberOfMessagesDelayed(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.ApproximateNumberOfMessagesDelayed.toString());
	}

	/**
	 * Set value of ApproximateNumberOfMessagesDelayed
	 * @param approximatenumberofmessagesdelayed
	 */
	public final void setApproximateNumberOfMessagesDelayed(java.lang.Integer approximatenumberofmessagesdelayed)
	{
		setApproximateNumberOfMessagesDelayed(getContext(), approximatenumberofmessagesdelayed);
	}

	/**
	 * Set value of ApproximateNumberOfMessagesDelayed
	 * @param context
	 * @param approximatenumberofmessagesdelayed
	 */
	public final void setApproximateNumberOfMessagesDelayed(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer approximatenumberofmessagesdelayed)
	{
		getMendixObject().setValue(context, MemberNames.ApproximateNumberOfMessagesDelayed.toString(), approximatenumberofmessagesdelayed);
	}

	/**
	 * @return value of ApproximateNumberOfMessagesNotVisible
	 */
	public final java.lang.Integer getApproximateNumberOfMessagesNotVisible()
	{
		return getApproximateNumberOfMessagesNotVisible(getContext());
	}

	/**
	 * @param context
	 * @return value of ApproximateNumberOfMessagesNotVisible
	 */
	public final java.lang.Integer getApproximateNumberOfMessagesNotVisible(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.ApproximateNumberOfMessagesNotVisible.toString());
	}

	/**
	 * Set value of ApproximateNumberOfMessagesNotVisible
	 * @param approximatenumberofmessagesnotvisible
	 */
	public final void setApproximateNumberOfMessagesNotVisible(java.lang.Integer approximatenumberofmessagesnotvisible)
	{
		setApproximateNumberOfMessagesNotVisible(getContext(), approximatenumberofmessagesnotvisible);
	}

	/**
	 * Set value of ApproximateNumberOfMessagesNotVisible
	 * @param context
	 * @param approximatenumberofmessagesnotvisible
	 */
	public final void setApproximateNumberOfMessagesNotVisible(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer approximatenumberofmessagesnotvisible)
	{
		getMendixObject().setValue(context, MemberNames.ApproximateNumberOfMessagesNotVisible.toString(), approximatenumberofmessagesnotvisible);
	}

	/**
	 * @return value of CreatedTimestamp
	 */
	public final java.util.Date getCreatedTimestamp()
	{
		return getCreatedTimestamp(getContext());
	}

	/**
	 * @param context
	 * @return value of CreatedTimestamp
	 */
	public final java.util.Date getCreatedTimestamp(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.CreatedTimestamp.toString());
	}

	/**
	 * Set value of CreatedTimestamp
	 * @param createdtimestamp
	 */
	public final void setCreatedTimestamp(java.util.Date createdtimestamp)
	{
		setCreatedTimestamp(getContext(), createdtimestamp);
	}

	/**
	 * Set value of CreatedTimestamp
	 * @param context
	 * @param createdtimestamp
	 */
	public final void setCreatedTimestamp(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date createdtimestamp)
	{
		getMendixObject().setValue(context, MemberNames.CreatedTimestamp.toString(), createdtimestamp);
	}

	/**
	 * @return value of DelaySeconds
	 */
	public final java.lang.Integer getDelaySeconds()
	{
		return getDelaySeconds(getContext());
	}

	/**
	 * @param context
	 * @return value of DelaySeconds
	 */
	public final java.lang.Integer getDelaySeconds(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.DelaySeconds.toString());
	}

	/**
	 * Set value of DelaySeconds
	 * @param delayseconds
	 */
	public final void setDelaySeconds(java.lang.Integer delayseconds)
	{
		setDelaySeconds(getContext(), delayseconds);
	}

	/**
	 * Set value of DelaySeconds
	 * @param context
	 * @param delayseconds
	 */
	public final void setDelaySeconds(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer delayseconds)
	{
		getMendixObject().setValue(context, MemberNames.DelaySeconds.toString(), delayseconds);
	}

	/**
	 * @return value of FIFOQueue
	 */
	public final java.lang.Boolean getFIFOQueue()
	{
		return getFIFOQueue(getContext());
	}

	/**
	 * @param context
	 * @return value of FIFOQueue
	 */
	public final java.lang.Boolean getFIFOQueue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.FIFOQueue.toString());
	}

	/**
	 * Set value of FIFOQueue
	 * @param fifoqueue
	 */
	public final void setFIFOQueue(java.lang.Boolean fifoqueue)
	{
		setFIFOQueue(getContext(), fifoqueue);
	}

	/**
	 * Set value of FIFOQueue
	 * @param context
	 * @param fifoqueue
	 */
	public final void setFIFOQueue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean fifoqueue)
	{
		getMendixObject().setValue(context, MemberNames.FIFOQueue.toString(), fifoqueue);
	}

	/**
	 * @return value of LastModifiedTimestamp
	 */
	public final java.util.Date getLastModifiedTimestamp()
	{
		return getLastModifiedTimestamp(getContext());
	}

	/**
	 * @param context
	 * @return value of LastModifiedTimestamp
	 */
	public final java.util.Date getLastModifiedTimestamp(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.LastModifiedTimestamp.toString());
	}

	/**
	 * Set value of LastModifiedTimestamp
	 * @param lastmodifiedtimestamp
	 */
	public final void setLastModifiedTimestamp(java.util.Date lastmodifiedtimestamp)
	{
		setLastModifiedTimestamp(getContext(), lastmodifiedtimestamp);
	}

	/**
	 * Set value of LastModifiedTimestamp
	 * @param context
	 * @param lastmodifiedtimestamp
	 */
	public final void setLastModifiedTimestamp(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date lastmodifiedtimestamp)
	{
		getMendixObject().setValue(context, MemberNames.LastModifiedTimestamp.toString(), lastmodifiedtimestamp);
	}

	/**
	 * @return value of MaximumMessageSize
	 */
	public final java.lang.Integer getMaximumMessageSize()
	{
		return getMaximumMessageSize(getContext());
	}

	/**
	 * @param context
	 * @return value of MaximumMessageSize
	 */
	public final java.lang.Integer getMaximumMessageSize(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.MaximumMessageSize.toString());
	}

	/**
	 * Set value of MaximumMessageSize
	 * @param maximummessagesize
	 */
	public final void setMaximumMessageSize(java.lang.Integer maximummessagesize)
	{
		setMaximumMessageSize(getContext(), maximummessagesize);
	}

	/**
	 * Set value of MaximumMessageSize
	 * @param context
	 * @param maximummessagesize
	 */
	public final void setMaximumMessageSize(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer maximummessagesize)
	{
		getMendixObject().setValue(context, MemberNames.MaximumMessageSize.toString(), maximummessagesize);
	}

	/**
	 * @return value of MessageRetentionPeriod
	 */
	public final java.lang.Integer getMessageRetentionPeriod()
	{
		return getMessageRetentionPeriod(getContext());
	}

	/**
	 * @param context
	 * @return value of MessageRetentionPeriod
	 */
	public final java.lang.Integer getMessageRetentionPeriod(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.MessageRetentionPeriod.toString());
	}

	/**
	 * Set value of MessageRetentionPeriod
	 * @param messageretentionperiod
	 */
	public final void setMessageRetentionPeriod(java.lang.Integer messageretentionperiod)
	{
		setMessageRetentionPeriod(getContext(), messageretentionperiod);
	}

	/**
	 * Set value of MessageRetentionPeriod
	 * @param context
	 * @param messageretentionperiod
	 */
	public final void setMessageRetentionPeriod(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer messageretentionperiod)
	{
		getMendixObject().setValue(context, MemberNames.MessageRetentionPeriod.toString(), messageretentionperiod);
	}

	/**
	 * @return value of ARN
	 */
	public final java.lang.String getARN()
	{
		return getARN(getContext());
	}

	/**
	 * @param context
	 * @return value of ARN
	 */
	public final java.lang.String getARN(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ARN.toString());
	}

	/**
	 * Set value of ARN
	 * @param arn
	 */
	public final void setARN(java.lang.String arn)
	{
		setARN(getContext(), arn);
	}

	/**
	 * Set value of ARN
	 * @param context
	 * @param arn
	 */
	public final void setARN(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String arn)
	{
		getMendixObject().setValue(context, MemberNames.ARN.toString(), arn);
	}

	/**
	 * @return value of VisibilityTimeout
	 */
	public final java.lang.Integer getVisibilityTimeout()
	{
		return getVisibilityTimeout(getContext());
	}

	/**
	 * @param context
	 * @return value of VisibilityTimeout
	 */
	public final java.lang.Integer getVisibilityTimeout(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.VisibilityTimeout.toString());
	}

	/**
	 * Set value of VisibilityTimeout
	 * @param visibilitytimeout
	 */
	public final void setVisibilityTimeout(java.lang.Integer visibilitytimeout)
	{
		setVisibilityTimeout(getContext(), visibilitytimeout);
	}

	/**
	 * Set value of VisibilityTimeout
	 * @param context
	 * @param visibilitytimeout
	 */
	public final void setVisibilityTimeout(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer visibilitytimeout)
	{
		getMendixObject().setValue(context, MemberNames.VisibilityTimeout.toString(), visibilitytimeout);
	}

	/**
	 * @return value of ReceiveMessageWaitTimeSeconds
	 */
	public final java.lang.Integer getReceiveMessageWaitTimeSeconds()
	{
		return getReceiveMessageWaitTimeSeconds(getContext());
	}

	/**
	 * @param context
	 * @return value of ReceiveMessageWaitTimeSeconds
	 */
	public final java.lang.Integer getReceiveMessageWaitTimeSeconds(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.ReceiveMessageWaitTimeSeconds.toString());
	}

	/**
	 * Set value of ReceiveMessageWaitTimeSeconds
	 * @param receivemessagewaittimeseconds
	 */
	public final void setReceiveMessageWaitTimeSeconds(java.lang.Integer receivemessagewaittimeseconds)
	{
		setReceiveMessageWaitTimeSeconds(getContext(), receivemessagewaittimeseconds);
	}

	/**
	 * Set value of ReceiveMessageWaitTimeSeconds
	 * @param context
	 * @param receivemessagewaittimeseconds
	 */
	public final void setReceiveMessageWaitTimeSeconds(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer receivemessagewaittimeseconds)
	{
		getMendixObject().setValue(context, MemberNames.ReceiveMessageWaitTimeSeconds.toString(), receivemessagewaittimeseconds);
	}

	/**
	 * @return value of QueueAttributes_Queue
	 */
	public final amazonsqsconnector.proxies.Queue getQueueAttributes_Queue() throws com.mendix.core.CoreException
	{
		return getQueueAttributes_Queue(getContext());
	}

	/**
	 * @param context
	 * @return value of QueueAttributes_Queue
	 */
	public final amazonsqsconnector.proxies.Queue getQueueAttributes_Queue(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		amazonsqsconnector.proxies.Queue result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.QueueAttributes_Queue.toString());
		if (identifier != null)
			result = amazonsqsconnector.proxies.Queue.load(context, identifier);
		return result;
	}

	/**
	 * Set value of QueueAttributes_Queue
	 * @param queueattributes_queue
	 */
	public final void setQueueAttributes_Queue(amazonsqsconnector.proxies.Queue queueattributes_queue)
	{
		setQueueAttributes_Queue(getContext(), queueattributes_queue);
	}

	/**
	 * Set value of QueueAttributes_Queue
	 * @param context
	 * @param queueattributes_queue
	 */
	public final void setQueueAttributes_Queue(com.mendix.systemwideinterfaces.core.IContext context, amazonsqsconnector.proxies.Queue queueattributes_queue)
	{
		if (queueattributes_queue == null)
			getMendixObject().setValue(context, MemberNames.QueueAttributes_Queue.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.QueueAttributes_Queue.toString(), queueattributes_queue.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return queueAttributesMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final amazonsqsconnector.proxies.QueueAttributes that = (amazonsqsconnector.proxies.QueueAttributes) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "AmazonSQSConnector.QueueAttributes";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
